[package]
name = "Reclaim"
version = "0.0.1"

edition = "2024.alpha" # To use the Move 2024 edition, currently in alpha

published-at = "0xbfd81ff7150e0e85be1daab249353b887f78b9b076c78675a8b09311e4cd2089"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }



[addresses]
reclaim =  "0x0"
